version: '3.7'
services:
  api:
    build:
      context: .
      target: build
      args:
        - RAKUTEN_APP_ID="1011959466247363309"
    ports:
      - "8090:8080"
    volumes:
      - .:/go/src/github.com/godiver/api
    command: ["fresh"]
