name: CI

on:
  push:
    branches: [master, feature/cd2, feature/cd3]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - id: auth
        name: authentication
        uses: google-github-actions/auth@v0.4.0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          access_token_lifetime: 300s

      # - name: 'Set up Cloud SDK'
      #   uses: 'google-github-actions/setup-gcloud@v0'

      - name: Push docker image
        run: |-
          gcloud auth login --brief --cred-file="${{ steps.auth.outputs.credentials_file_path }}"
          docker build . -t ${{ secrets.GCR_PRD }}:latest
          gcloud auth configure-docker ${{ secrets.GCR_PRD }}
          docker push ${{ secrets.GCR_PRD }}:latest

      - name: Logout
        run: |-
          gcloud auth revoke --all
