name: CI

on:
  push:
    branches: [master, feature/cd]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - id: auth
        name: authentication
        uses: google-github-actions/auth@v0.3.1
        env:
          GCP_SERVICE_ACCOUNT: ${{secret.GCP_SERVICE_ACCOUNT}}
          GCP_WORKLOAD_IDENTITY_PROVIDER: ${{secret.GCP_WORKLOAD_IDENTITY_PROVIDER}}
        with:
          token_format: access_token
          workload_identity_provider: ${{GCP_SERVICE_ACCOUNT}}
          service_account: ${{GCP_WORKLOAD_IDENTITY_PROVIDER}}

      - name: access
        run: echo "${{steps.auth.outputs}}"

      # - name: Set up Go
      #   uses: actions/setup-go@v2
      #   with:
      #     go-version: 1.15.7

      # - name: Build
      #   run: go build -v ./...
