name: CI

on:
  push:
    branches: [master]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: 'read'
  id-token: 'write'
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy-production:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2

      - id: auth
        name: authentication
        uses: google-github-actions/auth@v0
        with:
          workload_identity_provider: ${{ secrets.GCP_WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.GCP_SERVICE_ACCOUNT }}
          token_format: 'access_token'

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v0'

      - name: Configure docker to use the gcloud cli
        run: gcloud auth configure-docker --quiet

      - id: build
        name: Build docker image
        run: |-
          docker build . -t ${{ secrets.GCR_PRD }}:latest

      - name: Push docker image
        run: |-
          docker push ${{ secrets.GCR_PRD }}:latest

      - name: Update Cloud Run
        uses: 'google-github-actions/deploy-cloudrun@v0'
        with:
          service: 'booktube-api'
          image: ${{ secrets.GCR_PRD }}:latest
          region: 'asia-northeast1'
